plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.treadmill.bridge'
    compileSdk 33

    defaultConfig {
        applicationId "com.treadmill.bridge"
        minSdk 24
        targetSdk 33
        versionCode 23
        versionName "1.5.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }
}
